### ISSUE TITLE
Unable to get save from Star Tropics

### ISSUE THREAD

**Issue by plicease** [STOCD/OSCR#24]
I've been able to successfully get the save from other battery backup games, and to dump the ROM for Star Tropics, but when I try to get the save I get a message "RAM SIZE 0k".  I did verify that the cartridge and saves from way back in the day are working on a real life Nintendo, so the battery is not dead.

```
OSCR HW5 V14.3

[+] NES/Famicom


Searching database
for 508033DC or 2F5D7433...

NES CART READER

CURRENT SETTINGS

MAPPER:   4
PRG SIZE: 256K
CHR SIZE: 256K
RAM SIZE: 1K

Press Button...

[+] Read iNES Rom


Saving to NES/ROM/StarTropics/28/...
[*******************]
CRC32... 889129CB -> StarTropics (USA).nes

Press Button...

[+] Read Save

RAM SIZE 0K

Press Button...

[+] Read Save

RAM SIZE 0K

Press Button...
```

**Comment by sdellenb** [comment]
@plicease This is not the OSCR you're looking for. 😉 

It's a tool for parsing combat logs in Star Trek Online, unrelated to the Open Source Card Reader project.

**Comment by plicease** [comment]
> @plicease This is not the OSCR you're looking for. 😉
> 
> It's a tool for parsing combat logs in Star Trek Online, unrelated to the Open Source Card Reader project.

omg sorry, google fail!  Thanks for letting me know.
